name: Asynchronous CardDAV Sync (1 to 2)
on:
  schedule:
    - cron: '0 * * * *' # Run once every hour
  workflow_dispatch:   # Allow manual trigger via the GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    # environment: production # Use the environment for secrets and variables
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install vdirsyncer
        run: pip install vdirsyncer

      - name: Generate Config
        # Inject secrets and variables into the environment for envsubst
        env:
          NEXTCLOUD_URL: ${{ vars.NEXTCLOUD_URL }}
          NEXTCLOUD_USER: ${{ vars.NEXTCLOUD_USER }}
          NEXTCLOUD_PWD: ${{ secrets.NEXTCLOUD_PASSWORD }}
          NEXTCLOUD_COL: ${{ vars.NEXTCLOUD_COLLECTION }}
          MAILBOX_URL: ${{ vars.MAILBOX_URL }}
          MAILBOX_USER: ${{ vars.MAILBOX_USER }}
          MAILBOX_PWD: ${{ secrets.MAILBOX_PASSWORD }}
          MAILBOX_COL: ${{ vars.MAILBOX_COLLECTION }}
          GOOGLE_URL: ${{ vars.GOOGLE_URL }}
          GOOGLE_USER: ${{ vars.GOOGLE_USER }}
          GOOGLE_PWD: ${{ secrets.GOOGLE_PASSWORD }}
          GOOGLE_COL: ${{ vars.GOOGLE_COLLECTION }}          
        run: envsubst < vdirsyncer.config.template > config

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: status/
          key: vdir-status-${{ github.run_id }}
          restore-keys: vdir-status-

      - name: Execute Sync
        run: |
          mkdir -p status
          # "yes" automatically confirms the detection of new address book collections
          yes | vdirsyncer -c config discover
          vdirsyncer -c config sync

      - name: Save Cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: status/
          key: vdir-status-${{ github.run_id }}
