name: CardDAV Sync (G <> NC <> MB)
on:
  schedule:
    - cron: '0 * * * *' # Stündlich
  workflow_dispatch: # Manueller Start möglich

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install vdirsyncer
        run: |
          pip install vdirsyncer[google] aiohttp-oauthlib
      - name: Prepare Config
        run: |
          mkdir -p ~/.config/vdirsyncer/ ~/.vdirsyncer/status/
          # Token-Datei absolut minimalistisch erstellen
          cat <<EOF > ~/.vdirsyncer/google_token.json
          {
            "client_id": "${{ secrets.GOOGLE_CLIENT_ID }}",
            "client_secret": "${{ secrets.GOOGLE_CLIENT_SECRET }}",
            "refresh_token": "${{ secrets.GOOGLE_REFRESH_TOKEN }}",
            "token_type": "Bearer"
          }
          EOF
          envsubst < .vdirsyncer/config.template > ~/.config/vdirsyncer/config
      - name: Sync
        run: |
          # Nutze -vdebug für maximale Details
          yes | vdirsyncer -vdebug discover
          vdirsyncer -vdebug sync
